[[headers]]                                                                      
  for = "/dist/*.js"                                                             
  [headers.values]
    Content-Encoding = "js"
    Content-Type = "application/javascript"
  
[[headers]]                                                                      
  for = "/dist/*.js.gz"                                                             
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"